from pathlib import Path


def replace(path: str, old: str, new: str, count: int = 1) -> None:
    file = Path(path)
    text = file.read_text()
    actual = text.count(old)
    if actual != count:
        raise SystemExit(
            f"{path}: expected {count} occurrence(s), found {actual}: {old[:120]!r}"
        )
    file.write_text(text.replace(old, new, count))


replace(
    "scripts/seed.ts",
    'import { businessOnboardingDraft } from "../src/lib/database/schema/onboarding";\n',
    'import { businessTermsAcceptance } from "../src/lib/database/schema/business-governance";\n'
    'import {\n'
    '  businessCategorySection,\n'
    '  businessContactMethod,\n'
    '  businessEntitlement,\n'
    '  businessEvent,\n'
    '  businessLifecycle,\n'
    '  businessMenuGroup,\n'
    '  businessMenuItem,\n'
    '  businessOffer,\n'
    '} from "../src/lib/database/schema/business-operations";\n'
    'import { businessOnboardingDraft } from "../src/lib/database/schema/onboarding";\n',
)
replace(
    "scripts/seed.ts",
    '  publication: "00000000-0000-4000-8000-000000000901",\n',
    '  publication: "00000000-0000-4000-8000-000000000901",\n'
    '  contactEmail: "00000000-0000-4000-8000-000000001001",\n'
    '  contactEnquiry: "00000000-0000-4000-8000-000000001002",\n'
    '  offer: "00000000-0000-4000-8000-000000001101",\n'
    '  event: "00000000-0000-4000-8000-000000001201",\n'
    '  menuGroup: "00000000-0000-4000-8000-000000001301",\n'
    '  menuItem: "00000000-0000-4000-8000-000000001302",\n'
    '  categorySection: "00000000-0000-4000-8000-000000001303",\n'
    '  lifecycle: "00000000-0000-4000-8000-000000001304",\n'
    '  entitlement: "00000000-0000-4000-8000-000000001305",\n'
    '  termsAcceptance: "00000000-0000-4000-8000-000000001306",\n',
)

owner_permissions = '''[
          "business.view",
          "business.edit_profile",
          "business.publish",
        ]'''
full_owner_permissions = '''[
          "business.view",
          "business.edit_profile",
          "business.publish",
          "business.manage_members",
          "business.manage_contacts",
          "business.manage_enquiries",
          "business.manage_content",
          "business.manage_lifecycle",
          "business.view_analytics",
          "business.manage_claims",
        ]'''
replace("scripts/seed.ts", owner_permissions, full_owner_permissions, 4)
replace(
    "scripts/seed.ts",
    '        permissions: ["business.view"],\n',
    '        permissions: ["business.view", "business.view_analytics"],\n',
    2,
)

replace(
    "scripts/seed.ts",
    '  await database\n'
    '    .insert(businessPublication)\n'
    '    .values({\n'
    '      id: fixtureIds.publication,\n'
    '      businessId: fixtureIds.business,\n'
    '      businessSiteId: fixtureIds.site,\n'
    '      status: "published",\n'
    '      revisionNumber: 1,\n'
    '      publishedAt,\n'
    '      lastReviewedAt: publishedAt,\n'
    '    })\n'
    '    .onConflictDoUpdate({\n'
    '      target: businessPublication.businessId,\n'
    '      set: {\n'
    '        businessSiteId: fixtureIds.site,\n'
    '        status: "published",\n'
    '        revisionNumber: 1,\n'
    '        publishedAt,\n'
    '        lastReviewedAt: publishedAt,\n'
    '        updatedAt: sql`now()`,\n'
    '      },\n'
    '    });\n'
    '}\n',
    '  await database\n'
    '    .insert(businessPublication)\n'
    '    .values({\n'
    '      id: fixtureIds.publication,\n'
    '      businessId: fixtureIds.business,\n'
    '      businessSiteId: fixtureIds.site,\n'
    '      status: "published",\n'
    '      revisionNumber: 1,\n'
    '      publishedAt,\n'
    '      lastReviewedAt: publishedAt,\n'
    '    })\n'
    '    .onConflictDoUpdate({\n'
    '      target: businessPublication.businessId,\n'
    '      set: {\n'
    '        businessSiteId: fixtureIds.site,\n'
    '        status: "published",\n'
    '        revisionNumber: 1,\n'
    '        publishedAt,\n'
    '        lastReviewedAt: publishedAt,\n'
    '        updatedAt: sql`now()`,\n'
    '      },\n'
    '    });\n\n'
    '  await database\n'
    '    .insert(businessContactMethod)\n'
    '    .values([\n'
    '      {\n'
    '        id: fixtureIds.contactEmail,\n'
    '        businessId: fixtureIds.business,\n'
    '        type: "email",\n'
    '        label: "Email us",\n'
    '        value: "hello@cwm-coil.example",\n'
    '        enabled: true,\n'
    '        isPrimary: false,\n'
    '        sortOrder: 10,\n'
    '      },\n'
    '      {\n'
    '        id: fixtureIds.contactEnquiry,\n'
    '        businessId: fixtureIds.business,\n'
    '        type: "enquiry",\n'
    '        label: "Send an enquiry",\n'
    '        value: "form",\n'
    '        enabled: true,\n'
    '        isPrimary: true,\n'
    '        sortOrder: 20,\n'
    '      },\n'
    '    ])\n'
    '    .onConflictDoNothing();\n\n'
    '  await database\n'
    '    .insert(businessOffer)\n'
    '    .values({\n'
    '      id: fixtureIds.offer,\n'
    '      businessId: fixtureIds.business,\n'
    '      title: "Free fictional heating check conversation",\n'
    '      description:\n'
    '        "A demonstration offer showing how time-sensitive business content appears once on the business website.",\n'
    '      terms: "Demonstration only. No real service or discount is offered.",\n'
    '      status: "active",\n'
    '      sortOrder: 10,\n'
    '    })\n'
    '    .onConflictDoUpdate({\n'
    '      target: businessOffer.id,\n'
    '      set: { status: "active", updatedAt: sql`now()` },\n'
    '    });\n\n'
    '  await database\n'
    '    .insert(businessEvent)\n'
    '    .values({\n'
    '      id: fixtureIds.event,\n'
    '      businessId: fixtureIds.business,\n'
    '      title: "Fictional home-heating question session",\n'
    '      description:\n'
    '        "A clearly fictional future event used to prove one event can surface on both the business website and the shared events page.",\n'
    '      locationDisplay: "Online demonstration event",\n'
    '      startsAt: new Date("2099-02-14T18:00:00.000Z"),\n'
    '      endsAt: new Date("2099-02-14T19:00:00.000Z"),\n'
    '      status: "active",\n'
    '    })\n'
    '    .onConflictDoUpdate({\n'
    '      target: businessEvent.id,\n'
    '      set: { status: "active", updatedAt: sql`now()` },\n'
    '    });\n\n'
    '  await database\n'
    '    .insert(businessMenuGroup)\n'
    '    .values({\n'
    '      id: fixtureIds.menuGroup,\n'
    '      businessId: fixtureIds.business,\n'
    '      name: "Example maintenance options",\n'
    '      description: "A structured demonstration list, not a real price menu.",\n'
    '      sortOrder: 10,\n'
    '    })\n'
    '    .onConflictDoUpdate({\n'
    '      target: businessMenuGroup.id,\n'
    '      set: { status: "active", updatedAt: sql`now()` },\n'
    '    });\n\n'
    '  await database\n'
    '    .insert(businessMenuItem)\n'
    '    .values({\n'
    '      id: fixtureIds.menuItem,\n'
    '      businessId: fixtureIds.business,\n'
    '      groupId: fixtureIds.menuGroup,\n'
    '      name: "Demonstration boiler-care visit",\n'
    '      description: "Fictional structured content used for accessibility testing.",\n'
    '      priceDisplay: "Contact for guidance",\n'
    '      dietaryLabels: [],\n'
    '      available: true,\n'
    '      featured: true,\n'
    '      sortOrder: 10,\n'
    '    })\n'
    '    .onConflictDoUpdate({\n'
    '      target: businessMenuItem.id,\n'
    '      set: { available: true, updatedAt: sql`now()` },\n'
    '    });\n\n'
    '  await database\n'
    '    .insert(businessCategorySection)\n'
    '    .values({\n'
    '      id: fixtureIds.categorySection,\n'
    '      businessId: fixtureIds.business,\n'
    '      sectionType: "areas_covered",\n'
    '      title: "Example areas covered",\n'
    '      content: {\n'
    '        entries: [\n'
    '          {\n'
    '            title: "Rhondda",\n'
    '            description: "A fictional service-area example.",\n'
    '            meta: "Demonstration only",\n'
    '          },\n'
    '        ],\n'
    '      },\n'
    '      status: "active",\n'
    '      sortOrder: 10,\n'
    '    })\n'
    '    .onConflictDoUpdate({\n'
    '      target: businessCategorySection.id,\n'
    '      set: { status: "active", updatedAt: sql`now()` },\n'
    '    });\n\n'
    '  await database\n'
    '    .insert(businessLifecycle)\n'
    '    .values({\n'
    '      id: fixtureIds.lifecycle,\n'
    '      businessId: fixtureIds.business,\n'
    '      state: "active",\n'
    '      lastConfirmedAt: publishedAt,\n'
    '      nextConfirmationDueAt: new Date("2099-07-19T12:00:00.000Z"),\n'
    '    })\n'
    '    .onConflictDoUpdate({\n'
    '      target: businessLifecycle.businessId,\n'
    '      set: { state: "active", updatedAt: sql`now()` },\n'
    '    });\n\n'
    '  await database\n'
    '    .insert(businessEntitlement)\n'
    '    .values({\n'
    '      id: fixtureIds.entitlement,\n'
    '      businessId: fixtureIds.business,\n'
    '      planKey: "free",\n'
    '      capabilities: [\n'
    '        "website",\n'
    '        "directory",\n'
    '        "contacts",\n'
    '        "enquiries",\n'
    '        "offers",\n'
    '        "events",\n'
    '        "menu",\n'
    '        "category_sections",\n'
    '        "qr",\n'
    '        "basic_analytics",\n'
    '      ],\n'
    '      limits: {\n'
    '        galleryImages: 12,\n'
    '        logoImages: 1,\n'
    '        heroImages: 1,\n'
    '        teamMembers: 4,\n'
    '        locations: 1,\n'
    '        activeOffers: 10,\n'
    '        activeEvents: 25,\n'
    '      },\n'
    '    })\n'
    '    .onConflictDoUpdate({\n'
    '      target: businessEntitlement.businessId,\n'
    '      set: { planKey: "free", updatedAt: sql`now()` },\n'
    '    });\n\n'
    '  await database\n'
    '    .insert(businessTermsAcceptance)\n'
    '    .values({\n'
    '      id: fixtureIds.termsAcceptance,\n'
    '      businessId: fixtureIds.business,\n'
    '      acceptedByUserId: fixtureIds.owner,\n'
    '      termsVersion: "2026-07-21-v1",\n'
    '      acceptedAt: publishedAt,\n'
    '    })\n'
    '    .onConflictDoUpdate({\n'
    '      target: businessTermsAcceptance.businessId,\n'
    '      set: { termsVersion: "2026-07-21-v1", acceptedAt: publishedAt },\n'
    '    });\n'
    '}\n',
)
